### ISSUE TITLE
Distribute browser version  signals via npm as well

### ISSUE THREAD

**Issue by mrjjwright** [millermedeiros/js-signals#23]
I use npm to manage many of my client packages so if you distribute the browser based version of js-signals via NPM that would be great.  No biggie though and thanks for this great lib!

**Comment by millermedeiros** [comment]
not sure how to do that.. do you have any example of another project that does what you want? I also didn't understood how do you use the NPM files for the browser..

The easiest way that I can think right now is to change the closure wrapper and use the same version for browser and Node... something like this:

``` js
(function(exports){
  ...
  exports.signals = signals;
}((typeof module !== 'undefined' && module.exports? module.exports : null) || window || this));
```

But I'm trying to avoid adding complex wrappers, specially like [this one](http://www.sitepen.com/blog/2010/09/30/run-anywhere-javascript-modules-boilerplate-code/), that's why I created 3 different files.

**Comment by millermedeiros** [comment]
ohh... now I realized that you just want to keep the regular version of signals inside the package and I excluded it using the [.npmignore](https://github.com/millermedeiros/js-signals/blob/master/.npmignore) file...

still not sure how are you using the files and if it makes sense to keep the whole `/dist` folder since npm is target only for node...

**Comment by mrjjwright** [comment]
Exactly that will work. I wrote a cake task that parses my package.json dependencies and concatenates a JS file. I wrote a bit of an extension to package.json that specifies whether the file is local or in npm and I look inside node_modules for npm packages. I look inside lib, dist, or the root, so wherever you want to put it.

## Thanks! 

John Wright
Sent with Sparrow
