### ISSUE TITLE
use a linked list to store bindings and check perf

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/js-signals#42]
That is something I've been considering ever since v0.1, LinkedLists are usually faster in some types of operations because of the way they are constructed (no need to move all the items of the list to insert one in the middle). I didn't implemented it yet because **it only makes sense if the amount of listeners to a single event is HUGE** and that usually isn't the case (specially since each Signal is an individual event type), on all the times I used Signals on the past 1yr 1/2 _(n)_ was always small (under 100).

My current feeling is that the amount of code wouldn't pay-off the perf improvement on the edge case of having thousands of listeners to the same Signal, I'm also not sure how it would affect perf in a small _(n)_ (regular scenario).

Maybe keep it as a branch so user can choose which version to use in his case.

**Comment by millermedeiros** [comment]
implemented it quickly but didn't had time to check performance yet.

**Comment by r4j4h** [comment]
I haven't checked it out and done any tests myself, but just some food for thought: 

Perhaps it could be a switch flag on a Signal that can let the user choose on a per signal basis?

Or perhaps some "intelliswitching" could be implemented after performance tests so that if the number of subscribers hits a given threshold then it switches its logic. There would need to be some logic to protect against bouncing, as I presume switching from one storage format to the other would have a cost, and if the threshold was say 1,000 and you were at 999 and quickly added and removed a couple of handlers, you wouldn't want it converting back and forth automatically. Perhaps a large sigma type check, like that used in comparing floating point numbers could be of use, so they'd have to go down to like 980 after hitting the 1,000 mark to convert back? May be best to just leave it up to user to decide though.

**Comment by millermedeiros** [comment]
@r4j4h execution and filesize should be considered, I would be against keeping both storage methods, it should be one or the other. I still haven't profiled it, the current implementation is already VERY fast.

The linked list implementation could be even simpler (and faster) than the one I proposed 11 months ago, there are a lot of unnecessary method calls on 661a53b - the "fast linked list" isn't as "fast" as it could be...

Leaving it open in case someone want to do the tests and also because I was sure someone would ask for a pull request like this in the future.

**Comment by r4j4h** [comment]
Thanks for the feedback, I agree too. I've been using Signals in several projects and agree that it is very fast and usable as is.

Profiling sounds like the eventual final answer.
