### ISSUE TITLE
Error with IE9

### ISSUE THREAD

**Issue by sgentile** [millermedeiros/js-signals#45]
function validateListener(listener, fnName) {
    if (typeof listener !== 'function') {
        throw new Error('listener is a required param of {fn}() and should be a Function.'.replace('{fn}', fnName));
    }
}

is failing in IE 9 for me

perhaps the typeof check should be more like what is recommended here: 

http://stackoverflow.com/questions/5999998/how-can-i-check-if-a-javascript-variable-is-function-type

?

**Comment by sgentile** [comment]
perhaps the way I'm adding the listener is invalid, it works in other browsers, so I will report back more details of how I'm adding a listener

**Comment by sgentile** [comment]
I have validated - I get this error:
Line: 172
Error: listener is a required param of add() and should be a Function.

code:
var Signal = signals.Signal;

var errorNotification = {
    started: new Signal(),
    stopped: new Signal()
};
function onStarted(param1, param2) {
    alert(param1 + param2);
}

errorNotification.started.add(onStarted);
errorNotification.started.dispatch('foo', 'bar');

**Comment by sgentile** [comment]
my apologies, I discovered the actual source - the above did fire, but later in my code where I'm using hasher it was actually failing:

crossroads.routed.add(console.log, console); //log all routes

That failed in IE for me

**Comment by millermedeiros** [comment]
yes, `console.log` isn't a function on IE9 unless you have the dev tools opened. This check is exactly to avoid adding listeners that doesn't exist (fail early) but it is only really helpful when you see the call stack (so you can see which `add()` call that caused the issue).

PS: `typeof foo === "function"` works properly on all environments. `Array`, `Date` and `new Number`/`new String` that needs the `Object.prototype.toString.call()` check (since they all return `typeof` as `"object"`).
